version: "3.8"
services:
  skill:
    image: sleepy-helper-skill
    restart: always
    env_file:
      - .env
    environment:
      - DB_PROVIDER=postgres
      - POSTGRES_HOST=database
    depends_on:
      - database
      - migration
    networks:
      - skill_network
    ports: 
      - '5555:5555'

  migration:
    build: .
    image: sleepy-helper-skill
    depends_on: 
      - database
    command: bash -c "cd /app/skill/db/migrations && alembic upgrade head && cd /app"
    networks:
      - skill_network

  database:
    image: postgres:latest
    restart: always
    volumes:
      - skill-database-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - skill_network
    ports:
      - '5432:5432'

networks:
  skill_network:
    driver: bridge

volumes:
  skill-database-data:

