"""Initial

Revision ID: 13f56def336c
Revises: 
Create Date: 2023-03-25 22:31:06.656168

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '13f56def336c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description_text', sa.String(length=512), nullable=False),
    sa.Column('description_tts', sa.String(length=512), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occupation_time', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_text', sa.String(length=256), nullable=False),
    sa.Column('name_tts', sa.String(length=256), nullable=False),
    sa.Column('topic_description_text', sa.String(length=1024), nullable=False),
    sa.Column('topic_description_tts', sa.String(length=1024), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_skill_use', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_wake_up_time', sa.Time(), nullable=True),
    sa.Column('join_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('short_description_text', sa.String(length=256), nullable=False),
    sa.Column('short_description_tts', sa.String(length=256), nullable=False),
    sa.Column('tip_content_text', sa.String(length=1024), nullable=False),
    sa.Column('tip_content_tts', sa.String(length=1024), nullable=False),
    sa.Column('tips_topic_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tips_topic_id'], ['tips_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heard_tips',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tip_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tip_id'], ['tips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heard_tips')
    op.drop_table('tips')
    op.drop_table('users')
    op.drop_table('tips_topics')
    op.drop_table('activities')
    # ### end Alembic commands ###
