"""Added unique fields and indexes

Revision ID: 17ae56c4d705
Revises: 13f56def336c
Create Date: 2023-03-28 22:08:20.183143

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '17ae56c4d705'
down_revision = '13f56def336c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activities_description_text'), 'activities', ['description_text'], unique=True)
    op.create_index(op.f('ix_tips_short_description_text'), 'tips', ['short_description_text'], unique=True)
    op.create_index(op.f('ix_tips_tip_content_text'), 'tips', ['tip_content_text'], unique=True)
    op.create_index(op.f('ix_tips_topics_name_text'), 'tips_topics', ['name_text'], unique=True)
    op.create_index(op.f('ix_tips_topics_topic_description_text'), 'tips_topics', ['topic_description_text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tips_topics_topic_description_text'), table_name='tips_topics')
    op.drop_index(op.f('ix_tips_topics_name_text'), table_name='tips_topics')
    op.drop_index(op.f('ix_tips_tip_content_text'), table_name='tips')
    op.drop_index(op.f('ix_tips_short_description_text'), table_name='tips')
    op.drop_index(op.f('ix_activities_description_text'), table_name='activities')
    # ### end Alembic commands ###
